// <auto-generated />
using System;
using CCEAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CCEAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CCEAPI.Model.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Capital")
                        .HasColumnType("longtext");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("EstimatedGdp")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("FlagUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastRefreshedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("CCEAPI.Model.RefreshMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastRefreshedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TotalCountries")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RefreshMetadata");
                });
#pragma warning restore 612, 618
        }
    }
}
